sidebar <- bs4DashSidebar(status = "danger", expandOnHover = FALSE,
                          bs4SidebarMenu(id = "menu_principal",
                                         bs4SidebarMenuItem("Generalidades", icon = icon("clipboard-list"), selected = FALSE,
                                                            bs4SidebarMenuSubItem("Resumen Ejecutivo", tabName = "GE_Resumen", icon = icon("gauge-high")),
                                                            bs4SidebarMenuSubItem("Evolución del Negocio", tabName = "GE_Evolucion", icon = icon("chart-line")),
                                                            bs4SidebarMenuSubItem("Participación y Composición", tabName = "GE_Participacion", icon = icon("chart-pie")),
                                                            bs4SidebarMenuSubItem("Indicadores de Mercado", tabName = "GE_Indicadores", icon = icon("chart-column")),
                                                            bs4SidebarMenuSubItem("Comparación de Indicadores", tabName = "GE_Comparacion", icon = icon("chart-bar"))
                                         ),
                                         bs4SidebarMenuItem("Gestión Comercial", icon = icon("briefcase"), selected = FALSE,
                                                            bs4SidebarMenuSubItem("Oportunidades", tabName = "GC_Oportunidades", icon = icon("bullseye")),
                                                            bs4SidebarMenuSubItem("Pendientes de Gestión", tabName = "GC_Pendientes", icon = icon("list-check")),
                                                            bs4SidebarMenuSubItem("Notas y Tareas", tabName = "GC_Tareas", icon = icon("tasks")),
                                                            bs4SidebarMenuSubItem("Alertas y Notificaciones", tabName = "GC_Alertas", icon = icon("bell"))
                                         ),
                                         bs4SidebarMenuItem("Clientes", icon = icon("users"), selected = FALSE,
                                                            bs4SidebarMenuSubItem("Resumen", tabName = "CL_Resumen", icon = icon("list")),
                                                            bs4SidebarMenuSubItem("Ejecución Presupuesto", tabName = "CL_EjecucionPpto", icon = icon("money-bill-trend-up")),
                                                            bs4SidebarMenuSubItem("Potencial", tabName = "CL_Potencial", icon = icon("arrow-trend-up")),
                                                            bs4SidebarMenuSubItem("Comportamiento", tabName = "CL_Comportamiento", icon = icon("chart-area")),
                                                            bs4SidebarMenuSubItem("Fidelidad y Riesgo", tabName = "CL_Fidelidad", icon = icon("shield-halved")),
                                                            bs4SidebarMenuSubItem("Históricos", tabName = "CL_Historicos", icon = icon("clock-rotate-left")),
                                                            bs4SidebarMenuSubItem("Cartera", tabName = "CL_Cartera", icon = icon("file-invoice-dollar")),
                                                            bs4SidebarMenuSubItem("Segmentación", tabName = "CL_RFM", icon = icon("layer-group"))
                                         ),
                                         bs4SidebarMenuItem("Clientes a Recuperar", icon = icon("user-friends"), selected = FALSE,
                                                            bs4SidebarMenuSubItem("Resumen", tabName = "CR_Resumen", icon = icon("list")),
                                                            bs4SidebarMenuSubItem("Razones de Pérdida", tabName = "CR_Razones", icon = icon("circle-exclamation")),
                                                            bs4SidebarMenuSubItem("Oportunidades", tabName = "CR_Oportunidades", icon = icon("bullseye")),
                                                            bs4SidebarMenuSubItem("Seguimiento", tabName = "CR_Seguimiento", icon = icon("chart-line")),
                                                            bs4SidebarMenuSubItem("Segmentación", tabName = "CR_RFM", icon = icon("layer-group"))
                                         ),
                                         bs4SidebarMenuItem("Prospección", icon = icon("filter"), selected = FALSE,
                                                            bs4SidebarMenuSubItem("Kanban", tabName = "PR_Kanban", icon = icon("columns")),
                                                            bs4SidebarMenuSubItem("Contactos", tabName = "PR_Contactos", icon = icon("address-book")),
                                                            bs4SidebarMenuSubItem("Prospectos", tabName = "PR_Prospectos", icon = icon("handshake")),
                                                            bs4SidebarMenuSubItem("Leads", tabName = "PR_Leads", icon = icon("bullseye")),
                                                            bs4SidebarMenuSubItem("Descartados", tabName = "PR_Descartados", icon = icon("ban")),
                                                            bs4SidebarMenuSubItem("Conversión", tabName = "PR_Conversion", icon = icon("funnel-dollar")),
                                                            bs4SidebarMenuSubItem("Potencial de Mercado", tabName = "PR_Potencial", icon = icon("map-location-dot"))
                                         ),
                                         bs4SidebarMenuItem("Dinámica de Clientes", icon = icon("people-arrows"), selected = FALSE,
                                                            bs4SidebarMenuSubItem("Clientes Nuevos", tabName = "DC_Nuevos", icon = icon("user-plus")),
                                                            bs4SidebarMenuSubItem("Clientes Perdidos", tabName = "DC_Perdidos", icon = icon("user-minus"))
                                         ),
                                         bs4SidebarMenuItem("Cohortes de Clientes", icon = icon("chart-gantt"), selected = FALSE,
                                                            bs4SidebarMenuSubItem("Retención", tabName = "CO_Retencion", icon = icon("people-group")),
                                                            bs4SidebarMenuSubItem("Ventas", tabName = "CO_Ventas", icon = icon("chart-line")),
                                                            bs4SidebarMenuSubItem("Margen", tabName = "CO_Margen", icon = icon("dollar-sign")),
                                                            bs4SidebarMenuSubItem("Frecuencia", tabName = "CO_Frecuencia", icon = icon("clock"))
                                                            ),
                                         bs4SidebarMenuItem("Gestión por Asesor", icon = icon("user-tie"), selected = FALSE,
                                                            bs4SidebarMenuSubItem("Desempeño", tabName = "GA_Desempeno", icon = icon("chart-simple")),
                                                            bs4SidebarMenuSubItem("Ejecución Presupuesto", tabName = "GA_EjecucionPpto", icon = icon("money-bill-trend-up")),
                                                            bs4SidebarMenuSubItem("Bonificaciones", tabName = "GA_Bonificaciones", icon = icon("medal")),
                                                            bs4SidebarMenuSubItem("Oportunidades de Mejora", tabName = "GA_Mejora", icon = icon("arrow-up-right-dots"))
                                         ),
                                         bs4SidebarMenuItem("Información Cafetera", icon = icon("chart-line"), selected = FALSE,
                                                            bs4SidebarMenuSubItem("Mercado e Indicadores", tabName = "IC_Indicadores", icon = icon("chart-column")),
                                                            bs4SidebarMenuSubItem("Inventarios", tabName = "IC_Inventarios", icon = icon("boxes-stacked"))
                                         ),
                                         bs4SidebarMenuItem("Herramientas", icon = icon("screwdriver-wrench"), selected = FALSE,
                                                            bs4SidebarMenuSubItem("Calculadoras", tabName = "HE_Calculadoras", icon = icon("calculator")),
                                                            bs4SidebarMenuSubItem("Tablas de Conversión", tabName = "HE_Conversion", icon = icon("table")),
                                                            bs4SidebarMenuSubItem("Pendientes de Lotes", tabName = "HE_Pendientes", icon = icon("exclamation-triangle")),
                                                            bs4SidebarMenuSubItem("Informes", tabName = "HE_Informes", icon = icon("file-export"))
                                         ),
                                         bs4SidebarMenuItem("Consulta Individual", icon = icon("user"), tabName = "IN_Consulta")
                          )
)